version: '3.7'
services:
  clients:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=db
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  predictions:
    image: mongo:4.4
    ports:
         - 27017:27017
    environment:
         - MONGO_INITDB_DATABASE=predictions
    volumes:
         - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  bankcache:
      image: redis:6.0-alpine
      ports:
        - 6379:6379
      volumes:
        - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
